[theme]
base="dark"
primaryColor="#F63366"  # Streamlit's default accent pink/red used for toggles and sliders
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"